# Generated by Django 4.0.6 on 2023-01-03 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='dob',
            field=models.DateField(default=datetime.date.today, max_length=8),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_no',
            field=models.IntegerField(default=0, max_length=12),
        ),
    ]
