# Generated by Django 4.0.6 on 2023-01-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_teacher_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_feedback',
            name='reply_feedback',
            field=models.TextField(default=''),
        ),
    ]
