# Generated by Django 4.0.6 on 2023-01-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_teacher_feedback_reply_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_feedback',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
