# Generated by Django 4.0.6 on 2023-01-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_student_feedback_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_feedback',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
